"use client";
import { useEffect,useRef,useState } from "react";
import { parseTimeline } from "@/features/timeline/services/model";
import { timelineStorage } from "@/features/timeline/services/storage";
import { drawFrame,styles } from "@/features/visualization/services/engine";
import { exportMp4 } from "@/features/video-export/services/exporter";
import { exportEntitlement } from "@/features/follow-verification/services/entitlement.service";
import { onboardingState } from "@/features/onboarding/services/onboarding.service";
const target="@timelinevisualizer";
const fmt=n=>new Intl.NumberFormat().format(n);
export function AppShell(){const [screen,setScreen]=useState("loading"),[data,setData]=useState(null),[error,setError]=useState(""),[step,setStep]=useState(0),[style,setStyle]=useState("normal"),[duration,setDuration]=useState(10),[aspect,setAspect]=useState("square"),[unlocked,setUnlocked]=useState(false),[gate,setGate]=useState(false),[render,setRender]=useState(0),[notice,setNotice]=useState("");const file=useRef(),proof=useRef(),canvas=useRef();
useEffect(()=>{(async()=>{setUnlocked(exportEntitlement.isUnlocked());try{const saved=await timelineStorage.load();if(saved){setData(saved);setScreen(onboardingState.isComplete()?"import":"onboarding")}else setScreen(onboardingState.isComplete()?"import":"onboarding")}catch{setScreen("onboarding")}})()},[]);
useEffect(()=>{if(!data||!canvas.current)return;let f,run=true;const c=canvas.current,ctx=c.getContext("2d");const draw=t=>{drawFrame(ctx,c.width,c.height,data.points,(t%7000)/7000,style);if(run)f=requestAnimationFrame(draw)};f=requestAnimationFrame(draw);return()=>{run=false;cancelAnimationFrame(f)}},[data,style]);
const complete=()=>{onboardingState.complete();setScreen("import")};
const importFile=async e=>{const selected=e.target.files?.[0];if(!selected)return;if(selected.size>75*1024*1024)return setError("This file is too large. Choose a Timeline export smaller than 75 MB.");setError("");setNotice("Reading and normalizing your local Timeline…");try{const timeline=parseTimeline(JSON.parse(await selected.text()));await timelineStorage.save(timeline);setData(timeline);setScreen("dashboard");setNotice("")}catch(x){setNotice("");setError(x.message||"The selected file could not be processed.")}};
const verify=async e=>{const p=e.target.files?.[0];if(!p)return;setNotice("Verifying Follow Proof…");const form=new FormData();form.append("screenshot",p);try{const r=await fetch("/api/verify-follow",{method:"POST",body:form}),v=await r.json();if(v.valid){localStorage.setItem("timeline_mp4_export_unlocked","true");setUnlocked(true);setGate(false);setNotice("Export unlocked.")}else setNotice(v.reason)}catch{setNotice("Verification failed. Please try again.")}};
const exportVideo=async()=>{if(!unlocked)return setGate(true);if(duration<5||duration>90)return setNotice("Choose a duration between 5 and 90 seconds.");try{setRender(1);setNotice("Preparing MP4 render…");const blob=await exportMp4({points:data.points,style,duration:Number(duration),aspect,onProgress:setRender});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="my-timeline.mp4";a.click();URL.revokeObjectURL(a.href);setNotice("MP4 ready and downloaded.")}catch(e){setNotice(e.message)}finally{setRender(0)}};
if(screen==="loading")return <main className="center"><span className="loader"/> Loading your local studio…</main>;
if(screen==="onboarding"){const slides=[["YOUR JOURNEY, VISUALIZED.","Turn your places and routes into a moving visual story. Your Timeline stays on this device."],["IMPORT YOUR TIMELINE","Choose a Google Maps Timeline export. We never read Google Maps or its internal database."],["CHOOSE YOUR STORY","Normal, Travel, Transport, and Vehicle styles share one animation engine."],["EXPORT YOUR JOURNEY","Preview in your chosen format, then render an MP4 up to 90 seconds."]];const s=slides[step];return <main className="onboard"><nav><b>TV / 01</b><button onClick={complete}>Skip intro</button></nav><section><p className="eyebrow">TIMELINE VISUALIZER</p><h1>{s[0]}</h1><p>{s[1]}</p><div className="progress"><i style={{width:`${(step+1)/slides.length*100}%`}}/></div><button className="primary" onClick={()=>step===3?complete():setStep(step+1)}>{step===3?"Start Visualizing":"Continue"}</button></section><footer>LOCAL-FIRST · PRIVATE BY DEFAULT</footer></main>}
if(screen==="import")return <main className="import center"><div><p className="eyebrow">01 / IMPORT</p><h1>Bring your history<br/>into motion.</h1><p>Drop your Google Maps Timeline export here. It is parsed and stored only in your browser.</p><button className="drop" onClick={()=>file.current.click()}>Choose Timeline file <span>JSON</span></button><input ref={file} onChange={importFile} type="file" accept="application/json,.json" hidden/>{error&&<p className="error">{error}</p>}{notice&&<p>{notice}</p>}</div></main>;
return <main className="studio"><header><b>TV / 01</b><span>YOUR JOURNEY</span><button onClick={()=>{localStorage.removeItem("timeline_onboarding_completed");setScreen("onboarding")}}>Help</button></header><section className="map"><canvas ref={canvas} width="1000" height="650" aria-label="Animated route preview"/><div className="mapLabel">{data.summary.start?new Date(data.summary.start).toLocaleDateString():"Untimed route"} — {data.summary.end?new Date(data.summary.end).toLocaleDateString():"Today"}</div></section><aside><p className="eyebrow">VISUAL STORY</p><div className="styles">{Object.entries(styles).map(([id,label])=><button className={style===id?"selected":""} onClick={()=>setStyle(id)} key={id}>{label}</button>)}</div><div className="stats"><div><b>{fmt(data.summary.locations)}</b><span>locations</span></div><div><b>{data.summary.journeys}</b><span>journeys</span></div><div><b>{data.summary.distance.toFixed(0)} km</b><span>distance</span></div><div><b>{data.summary.places}</b><span>places</span></div></div><label>Duration <input type="number" min="5" max="90" value={duration} onChange={e=>setDuration(e.target.value)}/> sec</label><div className="styles"><button className={aspect==="portrait"?"selected":""} onClick={()=>setAspect("portrait")}>9:16</button><button className={aspect==="square"?"selected":""} onClick={()=>setAspect("square")}>1:1</button><button className={aspect==="landscape"?"selected":""} onClick={()=>setAspect("landscape")}>16:9</button></div><button className="primary export" disabled={!!render} onClick={exportVideo}>{render?`Rendering ${render}%`:`${unlocked?"Export MP4":"Unlock MP4 Export"}`}</button>{notice&&<p className="notice">{notice}</p>}</aside>{gate&&<div className="modal"><div><button className="close" onClick={()=>setGate(false)}>Close</button><p className="eyebrow">FOLLOW PROOF</p><h2>Unlock MP4 Export</h2><p>Follow <b>{target}</b>, then upload a clear Instagram screenshot that shows the account and Following status. We verify the screenshot only; we cannot inspect your Instagram account.</p><button className="primary" onClick={()=>proof.current.click()}>Upload proof screenshot</button><input ref={proof} type="file" accept="image/png,image/jpeg,image/webp" onChange={verify} hidden/></div></div>}</main>}
